# Generated by Django 2.2.6 on 2019-10-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(default='default.png', upload_to='')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
            ],
        ),
    ]
